#spring:
#  application:
#    name: service
#management:
##  endpoints:
##    jmx:
##      exposure:
##        include: *
##    web:
##      exposure:
##        include: *
#  endpoint:
#    health:
#      show-details: always
# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
# alibaba.cloud.access-key=****
# alibaba.cloud.secret-key=****
# 应用服务 WEB 访问端口
server:
  port: 8088
# Actuator Web 访问端口
management:
  server:
    port: 8081
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.service.dao

#配置
spring:
  #jdbc信息
  datasource:
    name: myself  #数据库名
    url: jdbc:mysql://localhost:3306/myTerritory?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8 #url
    username: root  #用户名
    password: 1  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
  #redis信息
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: 123456 #Redis服务器连接密码（默认为空）
    timeout: 2000ms #连接超时时间（毫秒）
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
#jwt配置
jwt:
  config:
    key: userLogin
    failureTime: 301000
#日志
logging:
  level:
    com.example.service.mapper: debug




